### ISSUE TITLE
Re: 2017-03-20, How would links work as proof?

### ISSUE THREAD

**Issue by mk-pmb** [Rosuav/rosuav.github.io#1]
Hi! In `_posts/2017-03-20-why-github-pages.md` you claim:

> if I try to rewrite git history to pretend I never said it, your link will be proof that I have done so.

How could a link be proof of anything? What kind of link would that be? Github will garbage-collect unreferenced commits after a while, so I don't see an improvement over the Internet Archive stuff. Maybe via Github notifications, but someone that interested could also engage a cloud service that monitors websites for changes.

**Comment by Rosuav** [comment]
If you can show in any way that the link once pointed somewhere, and it now points nowhere, then that's proof. Alternatively, just fork the repository, which will keep all of the commits untouched.

But you're looking at a fairly ancient repository that hasn't been touched in a long while - a project that I toyed with and then gave up on. The issue it was trying to solve IS still an issue, but the solution isn't a solution.
